### ISSUE TITLE
Issue in inferer.py with resizing.

### ISSUE THREAD

**Issue by mike-a-fischer** [pydsgz/DeepVOG#1]
The variable `resizing` is passed into `_preprocess_image` but in the body of the code, the variable `shape_correct` is passed which has opposite definition as resizing. Suggest changing resizing in the function definition to be `shape_correct` and change line 277 to be `if not shape_correct:`.

**Comment by yyhhoi** [comment]
Thank you a lot for spotting and reporting the bug! Yes, indeed, currently the behavior is opposite to what should be expected, i.e. frame is resized when not needed, and not resized when needed. Your suggested modifications have been incorporated.
